### ISSUE TITLE
Can't switch audio track in capture device playback

### ISSUE THREAD

**Issue by Rhiannon81** [clsid2/mpc-hc#1178]
Since 421bb7a capture device playback shows only one audio track named _Channel 1_ when the built-in audio switcher is enabled.

Disabling it, all the audio tracks show, named as _Format (Language)_

On the plus side, the normalize function which never worked for the capture device, now does.

**Comment by clsid2** [comment]
I don't have capture hardware, so I can't test this.

Make a debug build with and without the change. Compare the debug output of both builds.

**Comment by Rhiannon81** [comment]
Ok I have the debug builds, but it's not clear to me how to collect debug logs, could you please explain?

With the debug build, when opening a file or the capture device I get this error dialog, which is unrelated maybe.

Assertion failed
assert(prop.vt == VT_UI4);
in mpc-hc\src\thirdparty\sanear\src\AudioDeviceManager.cpp
at line 59

**Comment by clsid2** [comment]
It logs the output of all those TRACE lines. Visual Studio has an output tab where it show the log.
You can also see them with [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview).

That assert is probably unrelated.

**Comment by Rhiannon81** [comment]
[Logs.zip](https://github.com/clsid2/mpc-hc/files/6721410/Logs.zip)

That _assert failed_ happens only with the external (FireWire) audio device.

**Comment by Rhiannon81** [comment]
I also noticed that with the switcher on there are a lot of these lines

[13740] sanear: AudioDeviceEvent silence 1.22917 ms

Again, it is most likely unrelated to the problem at hand, but

- It happens only with audio switcher on
- It happens both with the FireWire and the integrated audio card 
- Apparently it happens only with AC3, not with MP2
- Doesn't always start consistently, might take a minute or 30, but once it starts it never stops
- When the silence is > ~40ms playback hangs completely
-  I can obviously hear pops and clicks

**Comment by clsid2** [comment]
Please ignore the sanear issues. Those are unrelated. Maybe switch to system default renderer to avoid those issues during debugging.

So the difference is that previously the audio switcher was not used, and now it gets inserted. I have committed a fix to block it again. It was blocked due to compatibility issues with DVB. It might be fixable to make it compatible, but I can't do that due to lack of hardware.

**Comment by Rhiannon81** [comment]
Tested the new commit but the audio switcher still gets inserted.

Sorry about all the unrelated stuff.

**Comment by clsid2** [comment]
Can you make another log with: do_log = true;

**Comment by clsid2** [comment]
If filter name differs, then try this change:
```
if (insert_clsid != GUID_NULL && insert_clsid == f.pFGF->GetCLSID() && pFGF->GetName() == f.pFGF->GetName()) {
            if (pFGF->GetMerit() < MERIT64_ABOVE_DSHOW || insert_clsid == __uuidof(CAudioSwitcherFilter)) {
```
->
```
if (insert_clsid != GUID_NULL && insert_clsid == f.pFGF->GetCLSID()) {
            if (pFGF->GetMerit() < MERIT64_ABOVE_DSHOW && pFGF->GetName() == f.pFGF->GetName() || insert_clsid == __uuidof(CAudioSwitcherFilter)) {
```

**Comment by clsid2** [comment]
The name indeed differs. I am fixing it now.

**Comment by Rhiannon81** [comment]
Yes that change works.
