### ISSUE TITLE
Aspect ratio problem with some renderers

### ISSUE THREAD

**Issue by ale5000-git** [clsid2/mpc-hc#1233]
[Here](https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/FGManager.cpp#L2614) it set the renderer for the preview based on the base renderer.

In the following cases you will see that in the first 2 rotation is supported correctly.
In the third rotation is not supported but it is still coherent so it is ok.
The problem is the fourth case where it is messed up.

See:

Base: MPC-VR Preview: EVR-CP
![MPC-VR](https://user-images.githubusercontent.com/15793015/127740188-645e5668-b0db-4a73-b9f8-b06bbaf55513.png)

Base: EVR-CP Preview: EVR-CP
![EVR-CP](https://user-images.githubusercontent.com/15793015/127740202-7b9be287-5007-4359-9cfb-95acd59417ef.png)

Base: EVR Preview: EVR
![EVR-normal](https://user-images.githubusercontent.com/15793015/127740211-4529bb80-9f7d-4a81-88ad-7733c11b4375.png)

Base: VMR9 (renderless) Preview: EVR
![VMR9](https://user-images.githubusercontent.com/15793015/127740229-634ac0ea-36c3-4f3d-a711-aa6116e2e056.png)

**Comment by ale5000-git** [comment]
Apparently only VMR9 (renderless) is affected instead VMR9 (windowed) and VMR7 are fine.

**Comment by VladWinner** [comment]
https://github.com/clsid2/mpc-hc/issues/1203
Fixed in 1.9.15

**Comment by ale5000-git** [comment]
No, it isn't fixed on case "Base: VMR9 (renderless) Preview: EVR", read the ticket carefully please.

**Comment by adipose** [comment]
Try this:

https://github.com/clsid2/mpc-hc/pull/1271
