### ISSUE TITLE
Play keyboard shortcut after mpc starts doesn't work

### ISSUE THREAD

**Issue by silverqx** [clsid2/mpc-hc#1301]
When I open mpc-hc it correctly remembers the last movie/playlist and the movie is stopped of course.

When I press the spacebar ( play keyboard shortcut ) nothing happens, I have to use the mouse and click on the play button.

When I click the play button by mouse, then the spacebar works as expected, every time.

**Comment by cw2** [comment]
It seems there is missing some command UI state update call - <kbd>Spacebar</kbd> does not work because Play menu commands are disabled.

**Comment by clsid2** [comment]
Fixed.

**Comment by silverqx** [comment]
I have tested it and it works great, thx @clsid2 🤙

**Comment by silverqx** [comment]
I can still reproduce this problem in a specific case @clsid2, steps to reproduce:
- open some movie
- check all Remember checkboxes in Options - Player - History 
- play movie ( this is not really needed )
- press Alt+enter to enter fullscreen mode
- press alt+f4 to close the player
- open mpc-hc again, last played movie and fullscreen should be remembered now
- press space to invoke play and nothing happens

I think the problem is that fullscreen mode 🐛.
