### ISSUE TITLE
[Bug] PGS subtitles rendered off screen on ultra wide monitor.

### ISSUE THREAD

**Issue by kissglay** [clsid2/mpc-hc#1476]
On a 3440x1440 monitor. Playing a movie (3840x2160) -- with black bars along the top and bottom, so its actual content being roughly 2.37:1 -- when using "touch window from outside" on fullscreen, the PGS subtitles are rendered below the screen (actually on the bottom black bar), so it's not visible.
But on windowed mode, it behaves as intended, rendering on the screen.
And option -- "Position subtitles relative to the video frame" only affects text subtitles, so text subtitles work well by tweaking it.

When played windowed, it works as intended:
![Windowed](https://user-images.githubusercontent.com/529385/148012776-2839238a-620b-4cce-acbc-bcb0e8eba4a2.png)

Info about "touch window from inside/outside":
![outside](https://user-images.githubusercontent.com/529385/148013154-a7933cc9-1944-4798-9c52-9e358ca6abac.png)
![inside](https://user-images.githubusercontent.com/529385/148013157-2e484a84-43cb-4afa-83b6-499f8f2d850f.png)

**Comment by clsid2** [comment]
Will look at this later. Only solution is to scale down the subtitles to visible video area.

As a workaround you can manually adjust the vertical position of the subs. Latest development build has new hotkeys to move subs up/down.

**Comment by kissglay** [comment]
Thx.
Already did that to lift the subtitle up.

**Comment by Max33Verstappen** [comment]
Starting from 1.9.19.34
PGS subtitles are no longer visible either with "touch window from inside" or with "touch window from outside"

**Comment by Max33Verstappen** [comment]
> Thx. Already did that to lift the subtitle up.

Moving subtitle up would also shift subtitles rendered on the top of the frame out of screen.

**Comment by ale5000-git** [comment]
Have you tried MPC-HC.1.9.19.42?

**Comment by clsid2** [comment]
I can reproduce the missing subs issue.

**Comment by clsid2** [comment]
Should be fixed or at least work better in 1.9.19.49

**Comment by Max33Verstappen** [comment]
I tried .49, but the PGS subs are still missing. Text based sub files are fine.

**Comment by clsid2** [comment]
I am unable to reproduce. Check that correct subtitle track is selected.

**Comment by Max33Verstappen** [comment]
I think setting "Sub picture to buffer" greater than 0 can reproduce the issue. Leaving it as "0" solves the issue.

**Comment by clsid2** [comment]
ok, I will check that

**Comment by Max33Verstappen** [comment]
> Should be fixed or at least work better in 1.9.19.49

The PGS subtitles are still rendered out of the screen on full screen (touching from outside) just like before. There's no difference at all. Or did I miss something or should I modify any settings?

**Comment by clsid2** [comment]
Try .51

**Comment by Max33Verstappen** [comment]
.51 fixes the subtitle missing issue. But... PGS subs are still rendered on the black bar, practically exactly the same as before (does it right when windowed but not when full screened). Fairly strange. MPC-BE and Potplayer both render it right.

**Comment by clsid2** [comment]
Inside the black bar is a normal place for subtitles. So that is the correct position. Most PGS subs have 1920x1080 resolution! It will be scaled down to fit in windowed mode when your video is cropped.

**Comment by Max33Verstappen** [comment]
![2022-03-07_09 10 16 824_mpc-hc64_Options](https://user-images.githubusercontent.com/97274607/156954563-d6af7ee6-728b-4403-a1de-28a10872b133.png)
Touch windows from outside:
When I have "Position subtitle relative to the video frame" checked, only text-based subs are affected, which means they are rendered on the black bar on both windowed and fullscreen. When it's unchecked, they're rendered relative to the screen position -- that is -- wouldn't be render on the black bar.
Is this option only for the text-based subs and has no effect on those rasterized ones?

And...You know, on an ultra-wide screen, if using "touch window from inside", a 21:9 movie placed in 16:9 frames looks like this, with so much wasted area.
![00040 mpls_snapshot_01 21 50 262](https://user-images.githubusercontent.com/97274607/156955465-5a8f1a98-7a2c-4ab3-afb8-29d46cbbb5d1.jpg)
So it would be great to have this option also work on rasterized subs.
Thx.

**Comment by clsid2** [comment]
Yes, it is for text subs only. I have no plans to change that. It would also not fix anything when black bars are part of the video!

MadVR has option to crop away black bars that are encoded in the video.

**Comment by Max33Verstappen** [comment]
Ok, then.
But may I ask why windowed mode and fullscreen are treated differently (both with "touch window from inside"), with the former respecting the current aspect ratio of view area, but the latter not, which is quite confusing when switching between the two modes. Shouldn't they be treated the same way?

**Comment by clsid2** [comment]
You need to make screenshots for me, because I don't think I understand what you mean.

Windowed and fullscreen are handled the same. So sizes must have different AR if you get different behavior.

**Comment by Max33Verstappen** [comment]
This is the same frame.
Windowed (Touch from outside):
![Windowed](https://user-images.githubusercontent.com/97274607/157040208-78ae8c83-2078-4437-b838-d1568cd52842.jpg)
Full Screen (Touch from outside):
![Fullscreen](https://user-images.githubusercontent.com/97274607/157040288-f9f629b5-04c8-4eda-ab8b-cf565f54bffe.jpg)

Windowed (Touch from inside):
![Windowed(Inside)](https://user-images.githubusercontent.com/97274607/157041037-44e613af-72ae-4aaa-b863-a0e862aeb949.png)
Full screen (Touch from inside):
![Fullscreen(Inside)](https://user-images.githubusercontent.com/97274607/157041581-8781a830-33e1-418c-945d-28ae68b75ab1.jpg)

**I made the aspect ratio of the rendering area of the windowed mode almost the same as the full screen (21:9).**
Please note that the video is encoded with black bars, so it's 16:9, and this subtitle is not rendered on the black bar for better observation of its position (because if it's rendered on the black bar, it isn't visible on full screen with "touch window from outside).

Can you see on full-screen mode, with "touch window from outside" and "touch window from inside", the subtitle is rendered on the same **position on the video frame**.
But on windowed mode, it's rendered **relative to the aspect ratio of the window**.

I hope I explained it clearly.
Thx

**Comment by Max33Verstappen** [comment]
And you can easily deduce that if subtitles are rendered on the black bar, they can be seen on the windowed mode but can't on full screen. (Both with "Touch window from outside").
This is what I mean about them being treated differently.

**Comment by Max33Verstappen** [comment]
This is what MPC-BE and Potplayer look like: (Note that the MPC-BE has option --"Position subtitle relative to the video frame" -- take effect on both text-based and rasterized subs, so here I unchecked it):

Full screen (Touch window from outside) (MPC-BE and Potplayer), and this is what is **consistent with the windowed mode (touch window from outside) on MPC-HC.**
![MPC-BE_Fullscreen(Outside)](https://user-images.githubusercontent.com/97274607/157046438-47eebee0-ef63-47cd-857a-19fde9717d2c.jpg)

**Comment by clsid2** [comment]
Are you sure that you are using the latest dev version? With "Touch from outside" the relative vertical position in the window stays the same for me. Subs do not disappear.

I will **not** change the positioning behavior relative to video frame. It uses "best fit" algorithm, and that stays that way. Period. MPC-BE/Potplayer will behave differently based whether the black bars were cropped or not. That is totally wrong as well.

**Comment by Max33Verstappen** [comment]
I tested using .51.
Did you test on an ultra-wide monitor? If the video is of the AR 16:9, "touch from outside" is no different from "touch from inside" on a 16:9/16:10 monitor.

--- edit ---
Unless you use a video of AR 4:3 on a 16:9/16:10 monitor, and you can find the subtitles are invisible (or cut off) when using "touch window from outside"

**Comment by Max33Verstappen** [comment]
When I "pan&scan"->move right/left/x/x frames in MPC-BE or Potplayer, the subtitles don't move around!!
When did the same thing, MPC-HC moves subtitles just like they are hardcoded in the video frames.

**Comment by ale5000-git** [comment]
@Max33Verstappen: The version to test is .55, not .51

**Comment by Max33Verstappen** [comment]
My bad. By the time I'm trying, the latest is .51. Don't know there's a new one.
Now so far so good.
Thx.
