### ISSUE TITLE
Prevent minimizing the player when in fullscreen on a non default monitor

### ISSUE THREAD

**Issue by chelpus** [clsid2/mpc-hc#1554]
"Prevent minimizing the player when in fullscreen on a non default monitor" not working.

**Comment by clsid2** [comment]
Fixed

**Comment by chelpus** [comment]
I checked this fix 1.9.19.21, but I still have the interface minimized when the video is opened in full screen on the second monitor. The fix doesn't work for some reason.
But thanks for trying :)
By the way, this was an very old mpc-hc problem, but D3D fullscreen used to solve the problem, but then it was disabled for madvr. I have to use the older version.

**Comment by clsid2** [comment]
This option is to prevent minimizing the video. For example when pressing Winkey+M.

Enable the trayicon option if you want a way access to the player on primary screen. Or enable "UseSMTC" in advanced options to control the player through the volume icon of Windows (requires Windows 10/11).

I am not interested in facilitating the ancient behavior of the past.

**Comment by chelpus** [comment]
These methods do not give access to the seekbar. All other controls are easy to implement with buttons, except for the sekbar.
I have no complaints about you and I understand that there is no free time for this. Thank you for your work, I'll have to continue to sit on version 1.6.8.
