### ISSUE TITLE
External subtitles don't follow changed playback rate of video

### ISSUE THREAD

**Issue by PPLToast** [clsid2/mpc-hc#1661]
If you speed up or slowdown the playback rate, external subs still go at 1x speed.

Tested with Internal Subtitle Renderer and AssFilter and the latest dev build 1.9.20.52.

This has been a thing since at least 2016 and possibly way longer, a post on doom9 mentions it.
http://forum.doom9.net/showthread.php?t=173794

**Comment by clsid2** [comment]
That was already fixed long ago. I just tested and it still works fine for me.

I only support internal subtitle renderer. All external ones are buggy.

**Comment by PPLToast** [comment]
Is there some specific setting I need to be toggling? I'm using .srt subs with mkv videos and it's still happening. I do use internal subtitle renderer.

Edit: Seems to be an issue with "Video Mixing Renderer 9 (renderless)" specifically. My bad.

**Comment by clsid2** [comment]
Fixed
