### ISSUE TITLE
[Bug] YDL video very slow seek with opus audio

### ISSUE THREAD

**Issue by bibsp** [clsid2/mpc-hc#1750]
This slowness is huge when you play movies or any long duration video. Completely unusable.
**My YDL settings:**
YDL max height: 1080
YDL format: 2

By default MPC-HC loads opus audio. But if You set YDL max height to 720 or lower then it loads aac audio. Then the player is fast and smooth. If you think my internet is not fast enough for 1080p videos then you are wrong.

Check with any long video like this: https://www.youtube.com/watch?v=6FqUN9MO0zc

Problem sample if you need:
720p aac audio, no problem: https://drive.google.com/file/d/1IY77rpi0KEaRFujDbw_iMIfvYMidwqQ-/view?usp=sharing
1080p opus audio, very slow: https://drive.google.com/file/d/1rbwA0oKvrorDQAzeCnbnf9GypZRIYbnP/view?usp=sharing

**Comment by clsid2** [comment]
Not a bug in the player. I can't fix it.

As you can see in the download speed in your systray, it downloads slower due to throttling done by youtube. They do that with the higher resolution stuff.

Use yt-dlp.exe instead of youtube-dl.exe. That suffers less from throttling.

**Comment by clsid2** [comment]
I might one day add option for preferred audio format in case separate audio streams are used.

**Comment by bibsp** [comment]
Already using yt-dlp.
When saving video with yt-dlp command inside mpc hc, no matter what resolution i choose to download. Download is super fast. Even 4k download is fast. It uses my full internet speed. You can try this.

1080p is bug free when playing with aac.

For this you need a long video which is just uploaded. Like game live streaming video. When i play such video then i noticed MPC-HC loads aac audio with 1080p. Then there is no lag.

I will try to find such video and and post it tomorrow if possible.

**Comment by Alp1821** [comment]
18 hours ago: https://www.youtube.com/watch?v=6NldcLDBRZI
1 hour ago: https://www.youtube.com/watch?v=2MYnQy0zrI4
Check these two streams in 1080p.

**Comment by clsid2** [comment]
I will add option for audio format.

It is not fault of player that seeking with opus is slow. VLC player also seeks slow with opus stream from youtube.

**Comment by bibsp** [comment]
YDL settings are messed up in latest test build. 1.9.21.59 x64.
I choose ydl height 1080, vid format 2, aud format 1. apply>ok.
Close player and next time launch player. Settings changed to 1080, 1, 0
This is happening even after resetting all settings in MPC-HC.

Edit: There are many things broken. Applied YDL aud format 2. Others are default. close player, relaunch. Then it's showing YDL vid format is set to 2

**Comment by clsid2** [comment]
Fixed

**Comment by bibsp** [comment]
Many things are still broken. **Things working properly are Video Height & Audio Format.**

**Video format is completely broken.**
From 1-6 opening VP90 only.
8 opening AV01 for 60 fps video.
8 opening AVC1 for 24 fps video. (Wrong)

With AVC1 which is now wrongly triggerd by 8, when video is 24 fps, then all resolution works except 720p. 720p giving long loading, then black screen. Means AVC1 720p not working.

It's very hard to describe. Revert the logic related to video format.
It was perfect in older versions.

**Comment by bibsp** [comment]
I noticed you changed some logic. Older MPC-HC's behavior was,
V height 0 (max)
V format 2 (avc1 60fps)
Player opens 1080p avc1 always, even the video is available in 4k or 8k vp9. It gives preference to format.

Now same setting, It opens 4k or 8k vp9 if available, else 1080p avc1.
It is giving preference to height.

I'm not against the current logic. Both are right. Maybe all those logical changes you made are not implemented correctly. So things are broken. If you don't have issue reverting everingthing might fix all issues.

**Comment by clsid2** [comment]
Bug with max height 0. As a workaround use explicit non-zero value for maximum.

**Comment by bibsp** [comment]
Even though i select 1080, prefer video format not working anymore.
Like 2 for avc 60
4 for vp9 60
Etc.....

Compare this build and previous stable build. You will understand.

I know workaround. But please fix all formats related issues before next stable release.

**Comment by clsid2** [comment]
Fixed

**Comment by bibsp** [comment]
> 720p giving long loading, then black screen. Means AVC1 720p not working.

Make sure you checked this bug also. It was very weird behavior.
Hoping for the best this time.
No need to reply.

**Comment by clsid2** [comment]
If a stream is broken it is fault of Youtube. I have seen that happen that some streams are not working.

**Comment by ale5000-git** [comment]
@Alp1821
If just some video formats are broken and others not, this should be reported to YDL (that may be able to detect and skip them).

**Comment by bibsp** [comment]
@ale5000-git I won't be able to explain to them. I don't have technical knowledge. You or someone else can report this to yt-dlp developer if you want. I can give you such link.

https://youtu.be/UHYUeZ8JszQ
Last time I checked this video. 720p avc1 was not working.

**Comment by clsid2** [comment]
That 720p stream is broken. Fault of Youtube. As I already said!!!
