### ISSUE TITLE
Help translating requested

### ISSUE THREAD

**Issue by adipose** [clsid2/mpc-hc#215]
The MPC-HC interface is about 98% translated.  Although the application isn't receiving too many new features, when it does it introduces new strings that need translating.  If you can help please sign up to translate here:

https://www.transifex.com/mpchc/mpchc/

Click here:

![image](https://user-images.githubusercontent.com/3324395/71769509-447b5080-2ed7-11ea-8485-b630396cb0a7.png)

Here is a help page on joining and helping out with the translations:

https://docs.transifex.com/getting-started-1/translators

**Comment by xknat** [comment]
Send in request to join for translating dutch

**Comment by adipose** [comment]
Thanks, I approved it.

**Comment by NightSharp** [comment]
@adipose I've send a request to join for Chinese (China)

**Comment by adipose** [comment]
@NightSharp you should have been approved now.

**Comment by NightSharp** [comment]
Thanks a lot
















At 2020-03-28 09:21:15, "adipose" <notifications@github.com> wrote:

@NightSharp you should have been approved now.

**Comment by ThePirate42** [comment]
In some of the english source strings this character can be found: &
Sometimes it is mid word. What does it mean?

**Comment by clsid2** [comment]
That is used for menu shortcuts. So if a menu contains an entry "&Play" you can activate that entry by pressing P while the menu is open.

When translating you can put the & in front of the same letter if the translated string has the same letter. If it doesn't have the same letter, then just remove the &.

**Comment by AlexStank** [comment]
@adipose I've send a request to join for Russian

**Comment by adipose** [comment]
@AlexStank , you should have been accepted now.

**Comment by moonlightz** [comment]
I sent a request to help translating to portuguese of portugal.

**Comment by adipose** [comment]
I approved it.  There is already pt_BR, so maybe you can start with that and update as needed.

**Comment by moonlightz** [comment]
Thankx. Portuguese of Brasil isn't my language of choice. When I'm using programs (like MPC-HC) or when using webpages like wikipedia, I switch to English if there isn't Portuguese of Portugal. Portuguese of Brasil is just a mix of Portuguese and latin-Spanish and then they tried to mimic'ed the english phrases form. Here in Portugal, we are now facing another silly language rectification which I think it is ridiculous and they are removing letters from the word we don't pronounce or they are lowercasing the initials of the months of the year or of the weekdays or the year seasons.
I know most part of MPC-HC and translation should be mid-easy.

**Comment by ThePirate42** [comment]
The latest release didn't include new transations, is this normal?

**Comment by adipose** [comment]
Until I sync and merge, they don't get included. I haven't merged them in a few weeks.

**Comment by lychichem** [comment]
> That is used for menu shortcuts. So if a menu contains an entry "&Play" you can activate that entry by pressing P while the menu is open.
> 
> When translating you can put the & in front of the same letter if the translated string has the same letter. If it doesn't have the same letter, then just remove the &.

I'm afraid that removing & will cause translated versions of MPC-HC lost the menu shortcut function. The best way is to use a (&) at the end of translated string. For example, &Play will be 播放(&P) after translated to Simplified Chinese.

**Comment by moonlightz** [comment]
lychichem hit a problem when Chinese and other languages don't use the normal 26 alphabet letters. 
Putting the shortcut letter between ( and ) with & is a good move.
I must say the key shortcuts for menu are hidden since ... XP(?)... maybe Vista and the user needs to have the option enabled to see them or when in a dialog an ALT will make them visible.
If the key shortcut can't be used, people which are translating strings, can see whole menu and decide and alternative letter in the string but the menu can't have 2 options with same letter for shortcut key.
I myself have such problem where half the strings lost the shortcut key.
I am almost finishing translating but translating is just the initial step. Then I will have to make lots and lots of corrections like the shortcut keys and make half of them to use other letters.
We are not forced to use the same letter as the English version.

Now...
I just would like to have mpc-hc translation online editor to tell me the max width of the string because some strings will be broken when displayed and theses strings will need to be shorten.

**Comment by lychichem** [comment]
> lychichem hit a problem when Chinese and other languages don't use the normal 26 alphabet letters.
> Putting the shortcut letter between ( and ) with & is a good move.
> I must say the key shortcuts for menu are hidden since ... XP(?)... maybe Vista and the user needs to have the option enabled to see them or when in a dialog an ALT will make them visible.
> If the key shortcut can't be used, people which are translating strings, can see whole menu and decide and alternative letter in the string but the menu can't have 2 options with same letter for shortcut key.
> I myself have such problem where half the strings lost the shortcut key.
> I am almost finishing translating but translating is just the initial step. Then I will have to make lots and lots of corrections like the shortcut keys and make half of them to use other letters.
> We are not forced to use the same letter as the English version.
> 
> Now...
> I just would like to have mpc-hc translation online editor to tell me the max width of the string because some strings will be broken when displayed and theses strings will need to be shorten.

Yes, certainly nobody force the translation usse the same shortcut, but for other l10n projects, usually the shortcuts are kept same. So not changing shortcut may be an arrangement.

As for strings max length, I have to tell you sadly that nearly no online platform can tell you. Some even can't tell you where the string will be displayed. I've tried manually calculate how many characters can be included in the display area by dividing item width/height givien in the resource files of the program and characters width/height. It's painful so I don't suggest you to do so like me. Maybe an improved string extractor which can extract the string as well as the position and size of its container will solve the problem (but I'm unable to make one for you).

**Comment by moonlightz** [comment]
1 way is to manually generate the dll file and check manually which are splitted to the next line and shrink strings as musch as possible. Checkboxes and labels usually split to the next line but if the height is not high enough, the rest of the text is not visible.

**Comment by clsid2** [comment]
> I'm afraid that removing & will cause translated versions of MPC-HC lost the menu shortcut function. The best way is to use a (&) at the end of translated string. For example, &Play will be 播放(&P) after translated to Simplified Chinese.

Please just remove menu shortcuts instead of adding letters behind the translations. Almost nobody uses these shortcuts anyway. They aren't visible by default either as moonlightz already mentioned.

**Comment by adipose** [comment]
Transifex translations should be up to date as of today, including adding Portugal.  Future updates will continue to come in every few weeks when I notice some additions.  When adding a new language I have to do a bit more work than just merging it, so be patient.

When it comes to string length, we went through a gui upgrade several months ago to allow much wider strings (particularly Russian) to fit where previously they could bleed outside the area.  So most strings should fit fine if you keep the translation reasonable.  For menus it should just expand to the string size.

As for shortcuts, I would focus on using ctrl/alt type shortcuts as much as possible.  If you can keep the underlined char the same, great, but otherwise just eliminate it.  The alternative is to review the entire menu or submenu and make sure all your shortcuts are unique (as possible).

**Comment by moonlightz** [comment]
I'm thinking of waiting for you to launch the pt-pt lang with next version of MPC-HC and then see the need of small corrections like proper context and shortening of some strings to fit and menu key shortcuts and that should take 1-2 days.
I included & in some menu options and removed where there wasn't a compatible letter as mentioned in a post above.
The & can be in some other letter as long as there is no duplicate in that specific menu.
Very few people will see these menu keys and use them daily. Either remove all or adapt them to the other letters, I would say.

**Comment by adipose** [comment]
I can make a test build.

**Comment by moonlightz** [comment]
Sure, if you don't mind.

**Comment by adipose** [comment]
@moonlightz , here you go, based on the latest transifex import.

https://mega.nz/file/4YZ1WC4K#Q7Lq5THTFbt6yaBy31aMuvdBps3k_AVtpksvImgDXYo

**Comment by moonlightz** [comment]
It seems you need to do it again. For some reason, the import got the work around where I was at the middle of the translation.

**Comment by adipose** [comment]
I just imported the newest translations.  Do you want another test build?

Are you saying the latest release didn't have the translations from the test build I made you?

**Comment by moonlightz** [comment]
Yep and yep.

**Comment by adipose** [comment]
https://mega.nz/file/JRgHwZbS#yEv077dwo6U2XbCxpQWTxAHQ6KU0h9NKxAlx-ukSC8I

This is built from the latest dev source.  It should hopefully have all the updated translations.

**Comment by moonlightz** [comment]
Problems are still there. No idea what's wrong. It should appear as they are translated in transifex but some strings aren't.
The Options dialog tree at left is messed up.

**Comment by adipose** [comment]
Can you send a screenshot of what it looks like, and what the right string should be?

**Comment by adipose** [comment]
@moonlightz , what is your transifex username?

**Comment by adipose** [comment]
Also the test build contains a lang folder with the language specific dlls. If you don't extract that, you won't get the update translations.

**Comment by adipose** [comment]
https://mega.nz/file/NApzDZxZ#UHFLf8tFJpOYRNT5lYCYSQEpoEhqOvf9L4Sa2_xoPps

Here's another test build.  I see more strings that came through from pt_PT.

**Comment by adipose** [comment]
I can see some english in the left pane, and I'm checking into it.

**Comment by adipose** [comment]
After reviewing it, it seems you are missing some translations that have been set to English somehow.

Here is one example (hopefully this search works for you):

https://www.transifex.com/mpchc/mpchc/translate/#pt_PT/src-mpc-hc-mpcresources-po-mpc-hc-strings-pot--transifex/190719923?q=text%3A'playback%3A%3Aoutput'

![image](https://user-images.githubusercontent.com/3324395/86041396-6f63de80-b9fa-11ea-9217-0b4f3ba2a40b.png)

This controls the title for "Output" here:

![image](https://user-images.githubusercontent.com/3324395/86041456-86a2cc00-b9fa-11ea-99dd-2a66c718d266.png)

**Comment by moonlightz** [comment]
Doing a search for :: , can see some items I left untranslated on purpose thinking that the items would get replaced by another string calls. Even so, some strings were changed after and it's like I say, they got stuck in a previous wave of translation.
I'm gonna translate those items with ::

**Comment by adipose** [comment]
It's possible I screwed up when merging them.  You could go through the commits to that file and see if it was ever reverted.  Or, you could just fix it.

I need to create a workflow that matches the transifex formatting, because every time a string is submitted, it alters the formatting of it, which creates confusing diffs for merging.  It might have caused an error on my end.

**Comment by moonlightz** [comment]
Ok, I translated the items with :: .
When I finished translation weeks ago, I made some changes after doing so. One of those changes was changing the string of Donate option menu from "Doar" to "Fazer uma doação", however, the translation you exported still had the first translation before correction.

**Comment by adipose** [comment]
I didn't get any new updates in the branch...hmm.

**Comment by moonlightz** [comment]
It seems I jumped some messages here...
My transifer username is hugo.simoes.1984
And yes, I extracted everything using 7zip to a folder, I see a folder named Lang.
![mpchc trans1](https://user-images.githubusercontent.com/34037569/86055951-8cc59680-ba54-11ea-899e-f26646b69e16.png)
I think no one mentioned this before but the underlined letters for shortcut keys of menus are invisible when dark theme is enabled.

**Comment by moonlightz** [comment]
Perhaps, I need to click on something... no idea.
Heres a screenshot...
![mpchc trans2](https://user-images.githubusercontent.com/34037569/86058017-14f96b00-ba58-11ea-8c0a-e702e5ef488f.png)
Transifer should give you the strings that are showing at right, the ones I translated.
And yes, Home Page could be translated but I left that one alone on purpose. Everyone here knows it will lead to the home page.

**Comment by adipose** [comment]
Something is wrong with the translations.  I think it has to do with the :: and the strings that define the tree.  Notice the tree branching has broken:

![image](https://user-images.githubusercontent.com/3324395/86058533-ebb7eb00-ba15-11ea-9723-d06d816c9b49.png)

**Comment by moonlightz** [comment]
Yep, It seems broken, that's why I left the strings with :: alone in first place. The translations I made today seem to have broken the tree. Any solution? Should I replace back the strings with :: ?

**Comment by adipose** [comment]
No, I will review it.

**Comment by moonlightz** [comment]
heh... I've been thinking and I think I screwed up. I fixed the strings now... I think. The tree should be ok now.

**Comment by adipose** [comment]
https://mega.nz/file/UZgzjbhJ#CcTe70yREkVuynBzmmqN-aauHfsPa_8YejRP7H0GzUk

Yes, it looks good now. Here is a build from the transifex branch.  If it looks good to you I will submit a PR.

**Comment by moonlightz** [comment]
Yeh, it's almost OK. There is a problem with "Internal filters", It's duplicated. Gonna try to fix the strings again.

**Comment by moonlightz** [comment]
I changed strings for Internal Filters and also made some more small corrections.
I also changed Subtitles::Misc translation to something that means Subtitles::More settings, to not confuse with miscellaneous at end of the tree. Brazillian also changed that Subtitles::Misc string.
Shaders is also a term that doesn't have a proper meaning for translation. Leaving it as is. Brazillian translation also left that as is. Hmm.. the braziilian translation looks messy... in some areas.. :P not my job to correct them.
It should be ok now for a new release. But I'm guessing I'm not done yet.

**Comment by adipose** [comment]
https://mega.nz/file/4RwjgLJB#vKf8wAPN2OBB-gHAayxGyTjNLmZivPdmJD_7gKDckFc

New build.

**Comment by moonlightz** [comment]
Great! The tree seems ok to me. Most of the things are ok as well and like I said, it will still need more smallish corrections like to short or enlarge strings. It will go over the time.

**Comment by adipose** [comment]
Sounds good, I submitted a PR for this.

**Comment by astankov84** [comment]
I would like to help translating MPC-HC in Bulgarian. This language is not in the list so I can't join in its team and also when I try to request it it says that is already requested. What is wrong there or I'm doing something not right?

**Comment by adipose** [comment]
@astankov84 check out this commit:

https://github.com/adipose/mpc-hc/commit/c1d9089a1ca9a8f7ded7db168e0ae54865075541

We would need a similar commit (ignore the non-pt_PT parts) to add a new language.  I'm busy at the moment, but if you can create all the updates for the Bulgarian and submit a PR, I can add it in transifex.

**Comment by astankov84** [comment]
I will try my best to translate it. Also I do have experience working with .po files from another software that I translated so you can give me those files and I can translate them and publish translation here.

**Comment by adipose** [comment]
Don't worry about the PO files or the translations. They can be filled out using Transifex. It's the rest of the files.

**Comment by astankov84** [comment]
> @astankov84 check out this commit:
> 
> [adipose@c1d9089](https://github.com/adipose/mpc-hc/commit/c1d9089a1ca9a8f7ded7db168e0ae54865075541)
> 
> We would need a similar commit (ignore the non-pt_PT parts) to add a new language. I'm busy at the moment, but if you can create all the updates for the Bulgarian and submit a PR, I can add it in transifex.

When you have time and feel comfortable please do what it is needed so I can start translating. I'm pretty new to github and still learning so that commit stuff is pretty difficult to understand right now and can't do it by myself. MPC-HC is the best software I used to play videos and I always been bothered why there is no Bulgarian which is my native language. Also I highly recommended it to my friends and they are bothered too so I think is time to do it by myself so I can contribute a little bit to my favorite software.

**Comment by adipose** [comment]
Sure, I will try to do it soon.

**Comment by astankov84** [comment]
> Sure, I will try to do it soon.

Thank you!

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/579

This will add it.  Once it is merged to develop I will bring it into this branch.

**Comment by astankov84** [comment]
> #579
> 
> This will add it. Once it is merged to develop I will bring it into this branch.

Getting closer and closer. Can't wait to see it in Transifex. Thanks again.

**Comment by adipose** [comment]
It should now be in transifex, too.

**Comment by astankov84** [comment]
> It should now be in transifex, too.

Yes it is and I send a join request.

**Comment by adipose** [comment]
Approved

**Comment by astankov84** [comment]
> Approved

Great. Now lets make one of my favorite software speak Bulgarian.

**Comment by adipose** [comment]
FYI--once I added Bulgarian, I got another request to translate from someone who has translated several other pieces of video related software.  I approved that as well, so hopefully you can work together on finishing up.

**Comment by astankov84** [comment]
> FYI--once I added Bulgarian, I got another request to translate from someone who has translated several other pieces of video related software. I approved that as well, so hopefully you can work together on finishing up.

That is just great having help is awesome! I did not expected that.

**Comment by astankov84** [comment]
I'm happy to announce that Bulgarian translation is now completed😊😊😊. Can't wait to see how it looks in real   👍👍👍

**Comment by astankov84** [comment]
In last preview build I finally saw the result of the translation and is pretty OK. There are some minor issues like too long translation on some strings that makes them partially invisible and of course typo and grammar errors that I will try to fix ASAP. For initial preview I think is pretty good  👍👍👍

**Comment by astankov84** [comment]
Can you please update the translations for the next test build so I can see any potential  Inaccuracies and fix them.
I already fixed some  Inaccuracies that I became aware of after the initial introduction of the Bulgarian language.

Thanks in advance!

**Comment by PCigales** [comment]
I have completed the translation into french.

**Comment by astankov84** [comment]
Thank you for the translation update 👍👍👍
I looked carefully at the translation and is pretty OK now. If I missed something it will be very insignificant.
You can now add it to the stable builds if you wish.

Have a nice day! (or evening or night depending of your location  😜)

**Comment by Felipefpl** [comment]
Clicked to join but no response so far, what happened?

**Comment by adipose** [comment]
> Clicked to join but no response so far, what happened?

I haven't reviewed it yet, but I will.

**Comment by adipose** [comment]
You should be approved, now.  Let me know if you have any trouble.

**Comment by Felipefpl** [comment]
It's working fine, thanks. :)

**Comment by Stackor** [comment]
Hey hey! 
Could you use a helping hand for the German translation?
I saw that some strings need translation, but German does not show up in the "Join Team" dialog on transifex.

**Comment by Felipefpl** [comment]
Talking of translations i saw mine wasnt added in the last build, was there a problem?

**Comment by adipose** [comment]
> 
> 
> Hey hey!
> Could you use a helping hand for the German translation?
> I saw that some strings need translation, but German does not show up in the "Join Team" dialog on transifex.

Hi, German is one of the languages on transifex, so I don't know why you wouldn't be able to join.  We currently have 7 members assigned to German.  If you give me your transifex username, I can try to add you manually.

Edit: I just approved you.  Not sure why it wasn't showing up as a request until now.

**Comment by adipose** [comment]
I did see someone requested German (de_DE).  We have German (de), I don't think we need localization for Germany itself do we?

**Comment by clsid2** [comment]
No, just standard German.

**Comment by ghost** [comment]
Hi,
thanks for the approval the other day.
I just completed the missing translations of all 4 resources of "German/Germany" on Transifex and updated them a little (with some comments) now as far as I could as a native German speaker, I hope.
Please look onto it when you got some leisure time.
Thank you all for your hard work for this best player ever on Windows OS.

**Comment by ShimiG** [comment]
Hi,
I sent a request to join the Hebrew translation team.

**Comment by ghost** [comment]
@ShimiG 
Hi,
I don't know if I can be of any help... I can only speak German, English and very little Japanese (which I am still learning as far as I got time for it).
And I don't really know anybody of my friends, relatives and acquaintances who speak this language or any other than the first two mentioned above.
My native language is German, but almost every application I use will be put in English because I'm used to it since almost 20 years. I can't get along with German, but for all German speaking people out there who wants to use it, I thought I help you with completing German because it wasn't finished until 3 days ago.

**Comment by adipose** [comment]
I approved both of you, I think.

**Comment by Felipefpl** [comment]
Hi, i noticed that the 4 pt-BR translations' files werent included in the latest release of mpc-hc, was there a problem with them?

**Comment by RonsonDk** [comment]
I can see Danish is only 94% done. If I try to join the team, Danish is missing.

When I go to the bottom to request a language, it says Danish is already added. Yet I still cannot choose it.

**Comment by adipose** [comment]
> Hi, i noticed that the 4 pt-BR translations' files werent included in the latest release of mpc-hc, was there a problem with them?

No, I have to merge translations before they get included. Just didn't do it yet.

**Comment by Felipefpl** [comment]
>No, I have to merge translations before they get included. Just didn't do it yet.

I see, thanks for the info.

**Comment by adipose** [comment]
@clsid2 , before release, you can message me and I'll try to get updated translations out in time for each release.

**Comment by clsid2** [comment]
@adipose, I might make a new release soon.

**Comment by adipose** [comment]
> 
> 
> @adipose, I might make a new release soon.

Forced synced.  Very few updates but a few showed up.  PR created.

**Comment by yamin8000** [comment]
Hi
I like to help completing translation for Persian (Iran), I already requested in Transifex.

**Comment by LYRIN-AR** [comment]
Hello,
I would like to complete Arabic translation. I've sent a request on transifex.

**Comment by adipose** [comment]
> 
> 
> Hi
> I like to help completing translation for Persian (Iran), I already requested in Transifex.

You should be accepted.  Note that persian is not a supported language at the moment.  Some set up is required and a patch submitted before the language will show up, even if you supply translations.  If you have time, review this thread where I've linked to other PRs for adding a language, and you can try to add Persian.

**Comment by adipose** [comment]
> 
> 
> Hello,
> I would like to complete Arabic translation. I've sent a request on transifex.

Accepted.

**Comment by hugok79** [comment]
@adipose I've sent a request on transifex a week ago. Portuguese (Portugal) language
My profile is: https://www.transifex.com/user/profile/hugok/

@clsid2 I haven't gotten a response here or on transifex yet.
Could you please solve this

**Comment by hugok79** [comment]
> @adipose I've sent a request on transifex a week ago. Portuguese (Portugal) language My profile is: https://www.transifex.com/user/profile/hugok/
> 
> @clsid2 I haven't gotten a response here or on transifex yet. Could you please solve this

Done! Thanks @adipose @clsid2

**Comment by adipose** [comment]
I approved all outstanding requests Saturday. You still have an outstanding request?

**Comment by hugok79** [comment]
No, my request has already been accepted.
I am already part of the translation team of Portuguese (Portugal)
Thank you @adipose

**Comment by Sp3EdeR** [comment]
I would like to join the MPCHC translation team to translate Hungarian strings. Unfortunately Transifex does not offer that as an available language to me. I'm not sure what I'm doing incorrectly.

**Comment by adipose** [comment]
If it's not an included language we need to add some new code, like this:

https://github.com/clsid2/mpc-hc/commit/351787f7ef909fac1ba7f6a74d25cb7ddd8aea6e

If you merge a similar block of code it will enable a new language.

**Comment by Sp3EdeR** [comment]
Oh. Nevermind. When I clicked the link, it seems it automatically sent a request to join teams I've set in my profile as known. It just failed to notify me about that.

**Comment by xLn2** [comment]
Is it possible to update latest translation changes to next dev release?

**Comment by hugok79** [comment]
Yes, I also think there should be a sync of the translation files from Transifex. I also made a few corrections and completed all the Portuguese (Portugal) translations since the last .pot update

**Comment by adipose** [comment]
Yes, I'll try to do it soon.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1646

**Comment by Sp3EdeR** [comment]
I have requested to join the Hungarian and English (UK/US) translation groups a few months ago on Transifex, but did not get accepted. Does anyone here know what could the reason be?

**Comment by adipose** [comment]
> I have requested to join the Hungarian and English (UK/US) translation groups a few months ago on Transifex, but did not get accepted. Does anyone here know what could the reason be?

Yes, I am too busy! Check it now.

**Comment by Sp3EdeR** [comment]
> > I have requested to join the Hungarian and English (UK/US) translation groups a few months ago on Transifex, but did not get accepted. Does anyone here know what could the reason be?
> 
> Yes, I am too busy! Check it now.

Thanks, I got the acceptance! :)

**Comment by hugok79** [comment]
> #1646
The translation in Transifex:
https://www.transifex.com/mpchc/mpchc/translate/#pt_PT/src-mpc-hc-mpcresources-po-mpc-hc-installer-strings-pot--transifex/190720751
The translation in MPC-HC code:
https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/mpcresources/PO/mpc-hc.installer.pt_PT.strings.po
This is not up to date.... someting is wrong!

**Comment by adipose** [comment]
> > #1646
> > The translation in Transifex:
> > https://www.transifex.com/mpchc/mpchc/translate/#pt_PT/src-mpc-hc-mpcresources-po-mpc-hc-installer-strings-pot--transifex/190720751
> > The translation in MPC-HC code:
> > https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/mpcresources/PO/mpc-hc.installer.pt_PT.strings.po
> > This is not up to date.... someting is wrong!

There is a bug with transifex, where it doesn't publish updated files, unless they hit 100%.  The bug is, if it was already 100%, and you update it, and it's still 100%, it never "hits" 100% again.  So it won't publish until there is a new, untranslated string added.  A workaround is to remove a good string and add it back.

The other workaround is to simply force sync all the translations, done or not.  I'm doing that now in case there were other missed ones.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/1651

**Comment by hugok79** [comment]
Ok. Thank you for the explanation.

**Comment by xLn2** [comment]
In Turkish translation, all command line parameter translation strings look like changed from "\t\t" to "⇥" I am just worried about it can cause any problem.
![resim](https://user-images.githubusercontent.com/3073922/161951168-a5fa842e-5059-455b-9619-19e50b96c77b.png)

**Comment by adipose** [comment]
> In Turkish translation, all command line parameter translation strings look like changed from "\t\t" to "⇥" I am just worried about it can cause any problem. ![resim](https://user-images.githubusercontent.com/3073922/161951168-a5fa842e-5059-455b-9619-19e50b96c77b.png)

Caused by copy/paste within transifex web page.  When displaying strings, it shows a unicode character to represent certain control characters. If you copy this string from the page, and paste it back in, it gets the actual unicode character instead of the control character!

Instead of copying, you must click on the control character in the UI, and it will put the same one below:

![image](https://user-images.githubusercontent.com/3324395/162042370-f42a90b4-373e-48de-92b1-8ebc2b74039a.png)

**Comment by adipose** [comment]
> In Turkish translation, all command line parameter translation strings look like changed from "\t\t" to "⇥" I am just worried about it can cause any problem. ![resim](https://user-images.githubusercontent.com/3073922/161951168-a5fa842e-5059-455b-9619-19e50b96c77b.png)

By the way, it should be fixed now.

**Comment by adipose** [comment]
> > > #1646
> > > The translation in Transifex:
> > > https://www.transifex.com/mpchc/mpchc/translate/#pt_PT/src-mpc-hc-mpcresources-po-mpc-hc-installer-strings-pot--transifex/190720751
> > > The translation in MPC-HC code:
> > > https://github.com/clsid2/mpc-hc/blob/develop/src/mpc-hc/mpcresources/PO/mpc-hc.installer.pt_PT.strings.po
> > > This is not up to date.... someting is wrong!
> 
> There is a bug with transifex, where it doesn't publish updated files, unless they hit 100%. The bug is, if it was already 100%, and you update it, and it's still 100%, it never "hits" 100% again. So it won't publish until there is a new, untranslated string added. A workaround is to remove a good string and add it back.
> 
> The other workaround is to simply force sync all the translations, done or not. I'm doing that now in case there were other missed ones.

This issue should be resolved for the future.  They just got back to me about a new option to force 100% translated items to sync when they are updated!

**Comment by McBaws** [comment]
I sent a request to help with Romanian translations

**Comment by adipose** [comment]
> I sent a request to help with Romanian translations

Approved

**Comment by kamild1996** [comment]
I wanted to help out with the Polish translation, which seems to be 96.3% done right now, but for some reason I cannot pick that language on the list on Transifex, how come?

**Comment by hugok79** [comment]
Maybe because you are already part of the Polish team

**Comment by kamild1996** [comment]
> Maybe because you are already part of the Polish team

Okay I rechecked my Transifex profile, apparently I did send a request at one point, I guess it was sent as soon as I first created my account but got no confirmation message about it, so I got confused. Nevermind :)

**Comment by adipose** [comment]
> > Maybe because you are already part of the Polish team
> 
> Okay I rechecked my Transifex profile, apparently I did send a request at one point, I guess it was sent as soon as I first created my account but got no confirmation message about it, so I got confused. Nevermind :)

I approved an outstanding request for Polish just now.

**Comment by Mami-Tomoe** [comment]
mt. hebrew req

**Comment by Hackjjang** [comment]
Send in request to join for translating Korean.

**Comment by adipose** [comment]
I have approved all outstanding translators.  If you still have not been accepted, go ahead and request to be a translator in Transifex.

**Comment by Hackjjang** [comment]
It's been about 3 months since I did the Korean translation, but... I got the Development Builds, but it doesn't seem to have the translation I worked on.
Will it be applied to the stable release or is there something else I need to do before then?

**Comment by clsid2** [comment]
You need to wait until adipose has time to merge the translation updates.

**Comment by adipose** [comment]
@Hackjjang 

Thanks for contributing.  I have merged transifex changes to this PR: https://github.com/clsid2/mpc-hc/pull/2112

**Comment by FacuGOLAZO** [comment]
I sent a request to help with spanish

**Comment by mikailreialt** [comment]
need to accept translating indonesia please. @adipose

**Comment by adipose** [comment]
> need to accept translating indonesia please. @adipose

Approved now.

**Comment by xLn2** [comment]
Some of Turkish translations didn't update for a while, at least I noticed few of them. For example "Allow overriding external splitter choice" string is not using last translation which is 1 year old.

**Comment by adipose** [comment]
I can check, but is the Turkish translation 100% complete?

By default, transifex doesn't push unless it is 100% complete.

**Comment by adipose** [comment]
> Some of Turkish translations didn't update for a while, at least I noticed few of them. For example "Allow overriding external splitter choice" string is not using last translation which is 1 year old.

I see 34 untranslated strings.  A few of them are old, I think...

We could push what we have, but if there's a translator, they should really finish!

**Comment by xLn2** [comment]
> > Some of Turkish translations didn't update for a while, at least I noticed few of them. For example "Allow overriding external splitter choice" string is not using last translation which is 1 year old.
> 
> I see 34 untranslated strings. A few of them are old, I think...
> 
> We could push what we have, but if there's a translator, they should really finish!

I translated or revised most of the parts but some of the strings are dull and technic for overall user, so I think its better to keep these as is.

**Comment by clsid2** [comment]
Then just copy the original string as the translated string. Then it counts as translated.

**Comment by adipose** [comment]
@xLn2 , I merged your latest updates.

**Comment by CoBC** [comment]
Hi, I sent a request for French. Thanks

**Comment by tsubasanouta** [comment]
Dear Adipose,
Would you please update transifex source files for PnS expressions when you have time?

**Comment by mikailreialt** [comment]
@adipose Indonesia translation Completed...

**Comment by adipose** [comment]
> @adipose Indonesia translation Completed...

https://github.com/clsid2/mpc-hc/pull/2425

Looks like it's included here!

**Comment by mikailreialt** [comment]
@adipose 
> This issue should be resolved for the future. They just got back to me about a new option to force 100% translated items to sync when they are updated!

indonesia 100% translated why is it not updated?

**Comment by CoBC** [comment]
Hi @adipose, what about my request for French translation please? Thanks

**Comment by adipose** [comment]
> Hi @adipose, what about my request for French translation please? Thanks

Approved.

**Comment by adipose** [comment]
> @adipose
> 
> > This issue should be resolved for the future. They just got back to me about a new option to force 100% translated items to sync when they are updated!
> 
> indonesia 100% translated why is it not updated?

What do you mean?  What's not updated?

**Comment by mikailreialt** [comment]
> > @adipose
> > > This issue should be resolved for the future. They just got back to me about a new option to force 100% translated items to sync when they are updated!
> > 
> > 
> > indonesia 100% translated why is it not updated?
> 
> What do you mean? What's not updated?

hmm never mind you already merged.. sorry!

**Comment by adipose** [comment]
Even after it gets pushed to the transifex branch I still have to make a PR and get it approved.

**Comment by xLn2** [comment]
There are many strings on Transifex that are obsolete and will never be used again, which is tiring for translators and creates problems for future translations. I think it would be useful to remove the strings that are not planned to be used again and to update the source language of some of the strings in accordance with today's terminology or some small typos.

I have prepared a list of my own, a short example of which is as follows. I will add my other findings if you are interested.

- Video size:										->				Resolution:
- Media length:									->				Media duration:
- Capture Settings								->				Recording Settings
- Rotate XYZ-+									->				Rotate XYZ-+ Axis
- Enables logging to file (requires restart)		->				+ file location?
- High precision									->				Show milliseconds
- Allow overriding external splitter choice        ->				Allow overriding LAV splitter choice / Override LAV splitter choice
- Audio time shift (ms):							->				Audio delay (ms): `//The use of delay has now become a given and is used in many places. At first, the word may sound like 'late', but people have probably gotten used to it.`

**Comment by Lukjan41** [comment]
Please accept me as a Polish translator, ljanik28,

**Comment by Lukjan41** [comment]
Please accept me as a Polish translator, ljanik28

**Comment by Lukjan41** [comment]
@adipose Please accept me as a Polish translator, ljanik28

**Comment by Lukjan41** [comment]
@clsid2 @adipose Please accept me as a Polish translator, ljanik28

**Comment by adipose** [comment]
Done.

**Comment by Lukjan41** [comment]
thank

**Comment by bosluk** [comment]
For Turkish translation, original translation belongs to me. Please give me access to transifex, so i can update the lang file. Regards.

**Comment by adipose** [comment]
> For Turkish translation, original translation belongs to me. Please give me access to transifex, so i can update the lang file. Regards.

Done

**Comment by Lukjan41** [comment]
the Polish language has been updated, what needs to be done now to make it available in mpc hc?

**Comment by Lukjan41** [comment]
@adipose The Polish language has been updated, what should I do now to make it available in mpc hc?

**Comment by clsid2** [comment]
You need to wait until we do a translation update. We usually only do that once every few months.

**Comment by Lukjan41** [comment]
pity :(

**Comment by Lukjan41** [comment]
@adipose @clsid2 please add the missing texts to be translated, because they are missing, e.g. in advanced (with clouds) and others in other options.

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2691

**Comment by Lukjan41** [comment]
There are still some bubbles to translate (hints)

**Comment by adipose** [comment]
> There are still some bubbles to translate (hints)

Examples?

**Comment by Lukjan41** [comment]
for example where it is checked and others in advanced.
![Bez tytułu](https://github.com/clsid2/mpc-hc/assets/163265642/1fddcb68-2812-4a29-aa97-48b50eabadd7)
when I wanted to take a screenshot, it disappears

**Comment by xLn2** [comment]
```

- [Invalid]
- [Local]
- Automatic
- Registered filter
- Error when dropping file
- Failed to load subtitle file
- Video Title Set Menu
- MPC Audio Renderer
- Audio Switcher
- Properties
- Insert deinterlace filter (blend) in capture mode
- Display duration in seconds for images rendered by Generate Still Video and MPC Image Source filters. Use 0 for infinite.
- Preferred audio format for stream that is selected from Youtube-DL results. Only applies if audio stream is separate from video stream.
0: Automatic
1: AAC
2: OPUS
```

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/2694

Fixes missing ones from advanced.

**Comment by Lukjan41** [comment]
thank

**Comment by adipose** [comment]
> thank

Those advanced strings should be merged to transifex now.

**Comment by Lukjan41** [comment]
thanks for the info.

If I find something else, I will provide a screenshot and write, after updating in mpc hc

**Comment by shooterspps** [comment]
I found it. I'm in.

**Comment by Lukjan41** [comment]
@adipose Is there a chance for the language files to be updated every two or three stable versions of mpc hc to match? I am a translator

**Comment by clsid2** [comment]
They are updated when they are updated.

Stop being annoying or you will be removed as translator.

**Comment by Lukjan41** [comment]
ok, I want to translate the program as best as I can.

**Comment by tsubasanouta** [comment]
Could you improve "/fixedsize w,h Set a fixed window size" when you have time?
/fixedsize w,h[,x,y]	Set a fixed window size; optionally specificy upper-left window position

**Comment by NarloxT** [comment]
I've sent a request to help with the Arabic language.
