### ISSUE TITLE
Ignore ASS subtitles errors

### ISSUE THREAD

**Issue by joric** [clsid2/mpc-hc#2500]
Can't play these embedded ASS subtitles in mplayerc. VLC player plays them just fine. Subtitle edit gives error:
```
Number of expected Style elements do not match number of Format elements:
Style: Default,Arial,16,&Hffffff,&Hffffff,&H0,&H0,0,0,0,1,1,0,2,10,10,10,0,0,1,1,1,
```
Can we ignore this error in mplayerc, akin to VLC? It kind of makes sense if we ignore style we do not use.
I'm not sure where these errors come from but it's a whole bunch of videos lately, must be a popular tool.

Subtitles attached.
[[pseudo] Rick and Morty S02E06 The Ricks Must be Crazy [1080p] [h.265]_track3_[eng].ass.zip](https://github.com/clsid2/mpc-hc/files/14071091/pseudo.Rick.and.Morty.S02E06.The.Ricks.Must.be.Crazy.1080p.h.265._track3_.eng.ass.zip)

**Comment by clsid2** [comment]
Fixed

**Comment by joric** [comment]
@clsid2 something's still off. I can use those subtitles as a sideload but embedded ones are still not showing, maybe there's a different code for the mkv loader and an external loader? Torrent in question https://thepiratebay.org/description.php?id=12678054

**Comment by clsid2** [comment]
Fixed again in 2.1.5.22

**Comment by joric** [comment]
Downloaded 2.1.5.22 from releases, still doesn't work =( Subtitles are enabled but no text on screen. Save subtitles is inactive also.
![Screenshot (36)](https://github.com/clsid2/mpc-hc/assets/852547/cabb8244-a001-4d8b-ad66-2f1de05132e2)

**Comment by clsid2** [comment]
Tested only with the external sub. I see another fix is needed for embedded one. Will fix that later.

**Comment by joric** [comment]
Confirmed to work with 2.1.6, all good!
