### ISSUE TITLE
media player classic encountered an improper argument mpc-hc

### ISSUE THREAD

**Issue by 4lt3r3go** [clsid2/mpc-hc#3213]
this happens when exif metadata are saved in the video.
i use ComfyUI (AI interface) that saves video with baked workflow in the exif.
unfortunaly i cant use mediaplayer classic because of this.
the video is playing but this error keep stay in the front and keep repeating the error message to infinite.

**Comment by clsid2** [comment]
Upload a sample file.

**Comment by 4lt3r3go** [comment]
https://github.com/user-attachments/assets/16afb7d8-aa2f-41c2-a07a-c6970c3106e0

I also uploaded the file in a ZIP version, as it often happens that some platforms automatically remove metadata from videos once they are uploaded. So, if you can't reproduce the error, use the file contained in the ZIP

[MPC.zip](https://github.com/user-attachments/files/18152864/MPC.zip)

**Comment by 4lt3r3go** [comment]
If it can help in any way:
I use this small tool [(link)](https://exiftool.org/) to remove the EXIF metadata from the video so that MPC can display it properly.
However, I would prefer not to do this since the metadata is extremely important for the software I use.

_also notice: this error is present also in the other mediaplayer by Guliverkli_

**Comment by clsid2** [comment]
Fixed

**Comment by 4lt3r3go** [comment]
Thanks. ComfyUI community will really love this update, let me spread the word! 
i see last release is from 3 weeks ago, should i wait a new release to have this fix?

**Comment by chille9** [comment]
Still getting this error with some comfyui videos even with the latest updated version.
(x64)

**Comment by clsid2** [comment]
Upload sample

**Comment by chille9** [comment]
![Image](https://github.com/user-attachments/assets/d789805a-e956-4c30-a255-4a3d1fd41762)
Seems to happen still with the same sample provided as above by 4lt3r3go! Should be related to the metadata embeded.

**Comment by clsid2** [comment]
That sample does not give an error here.

Which version are you using? Because I almost certain that you are not using the latest one (2.4.2).

**Comment by chille9** [comment]
> That sample does not give an error here.
> 
> Which version are you using? Because I almost certain that you are not using the latest one (2.4.2).

I tried both 2.4.2 and the latest nightly. I think i´ve narrowed down the issue. And you´re right in that it is an error related to the version.
When I open an mp4 file by double clicking and checking "about" it uses an older version of mpc-hc-x64 **_regardless_** of opening with the exe of the **_new_** (2.4.2) installation.
I even tried un-installing mpc completely but there must be an old version that doesnt get deleted somewhere.

Okay the issue was caused by,
### K-lite codec. 
This was installed in C: and windows used this mpc exe **_instead_** of the freshly installed one. So for those with this error make sure to completely uninstall K-lite as well!

**Comment by clsid2** [comment]
If you double-click on a file in explorer, it uses whatever application is tied to the file association. Just installing MPC-HC does not create or change any file associations. That is a separate step.

Latest version of MPC-HC is included with latest version of K-Lite.

**Comment by chille9** [comment]
> If you double-click on a file in explorer, it uses whatever application is tied to the file association. Just installing MPC-HC does not create or change any file associations. That is a separate step.
> 
> Latest version of MPC-HC is included with latest version of K-Lite.

Thats the weird thing since I did change the file association manually to the 2.4.2 mpc exe by right clicking > properties etc.

**Comment by clsid2** [comment]
There are no file association related settings in explorer properties submenu. I am not sure what you did, but it is not correct.

I suggest you just update K-Lite and it will do everything for you.
