### ISSUE TITLE
DVD playback speed issue with internal audio renderer

### ISSUE THREAD

**Issue by clsid2** [clsid2/mpc-hc#584]
@adipose

I have gotten a few reports about this. Playback sometimes speeds up or slows down at start of a title on the disc. Happens only with internal audio renderer. Probably related to the clock fix we did for MPCVR,

Seems to happen on titles where audio starts later than the video.

**Comment by lifegpc** [comment]
[2020-08-19 22-51-23.zip](https://github.com/clsid2/mpc-hc/files/5097261/2020-08-19.22-51-23.zip)
This is another problem that caused by internal audio renderer that may related to this issue.
The DVD is the same in #464 . (File : https://1drv.ms/u/s!Aoq8mAMlVv8Ul1tXuHPKJlDTuEwO?e=3Uy59p )
Filters currently loaded:
  - Internal Audio Renderer
  - EVR (自定义呈现器)
  - Audio Switcher
  - LAV Video Decoder (internal)
  - LAV Audio Decoder
  - DVD Navigator

**Comment by lifegpc** [comment]
The playback speed is too fast in this situation.

**Comment by adipose** [comment]
@clsid2 hmm, I will look into it.  I wouldn't be surprised if it's related to that fix, either.

@lifegpc, so the original DVD with the menu problem now has a speed problem?  How can I verify it easily?

**Comment by lifegpc** [comment]
Just play a title for a while will have this issue.
![image](https://user-images.githubusercontent.com/41434272/90703019-43a8fa80-e2bf-11ea-9e7a-df386293d367.png)
![image](https://user-images.githubusercontent.com/41434272/90703034-4f94bc80-e2bf-11ea-9a1b-9ba1779bb2cb.png)

**Comment by lifegpc** [comment]
@adipose I try play another DVD. If MPC-HC play a title directly, it works fine(But pause playback a while, and keep play still have problem). If I play a title from DVD menu or choose a title from Navigate menu, this issue occurs.

**Comment by lifegpc** [comment]
> @adipose I try play another DVD. If MPC-HC play a title directly, it works fine(But pause playback a while, and keep play still have problem). If I play a title from DVD menu or choose a title from Navigate menu, this issue occurs.

The DVD file: https://1drv.ms/u/s!Aoq8mAMlVv8UmlHwRch7FsWmk_Qg?e=AZQ2IW

**Comment by adipose** [comment]
@lifegpc @clsid2 

I disabled the title menu fix in this build.  Audio seems fine, now.  But I cannot reproduce the old bug, either.  Can either of you?

Maybe it was fixed somehow in LAVFilters?  I'm mystified.

Please test:

https://mega.nz/file/4JozEaRK#yucTKkZHCo96i94cWn1bnudx_PVttrivjDwDHUpmSvM

**Comment by lifegpc** [comment]
@adipose The bug in #464 still occurs when I use this test build.

**Comment by adipose** [comment]
At least it's consistent.  I can't get it to fail at the moment.

**Comment by adipose** [comment]
Nevermind, it still fails with MPC-VR.  In fact, it's now crashing on me at the menu in DX9 mode.

**Comment by adipose** [comment]
https://mega.nz/file/ZBojyACA#3i3hv0_a9hvrpKxg2rmak0sAAITenWg5cvQFIuh1kBo

Try this build, and let me know how it behaves for both issues.

**Comment by lifegpc** [comment]
It works fine with EVR-CP and MPC-VR.

**Comment by adipose** [comment]
Great.  I hope this resolves all the issues without any regressions.  It's now more limited in what it changes when using DVD, and DX11 mode also seems to work.

@clsid2 , can you confirm DX11 is working ok for you too?

**Comment by clsid2** [comment]
Yes, seems ok now.
