### ISSUE TITLE
More libass/libfontconfig issues in VS 2017

### ISSUE THREAD

**Issue by kenny1983** [clsid2/mpc-hc#833]
Hi all!

Like the OP of https://github.com/clsid2/mpc-hc/issues/772 I would like to make some minor changes to this project, but am having major issues getting it to compile (please also see https://github.com/clsid2/mpc-hc/issues/829 for more details on that).

My most-recent issue seems to be related to the first issue linked above, but my exact error message is slightly different (complex root path removed for brevity):
```
Severity  Code     Description                                               Project  File                                                      Line
Error     LNK1241  resource file freetype2.lib(ftver.res) already specified  libass   mpc-hc\src\thirdparty\libass\libfontconfig.lib(ftver.res)	1
```
As mentioned in the title, I'm using VS 2017 (15.9.30 to be exact) because 16.8.3 causes a plethora of other build issues. I managed to fix most of those on my own before giving up and creating the second issue linked above. I'm now able to build in Release Lite configuration, but not Debug Lite. 

@clsid2 was kind enough to provide a 16.6.4 installer, but sadly it doesn't work either. MS has shifted to using a web-based installer called Visual Studio Installer - this is probably not news to any of you, but what seems to be unknown (to me at least, until now) is that it now forces the most recent release of a major version upon its users.

So if anyone knows of a way to download an offline installer for said version, or better yet, nuke Visual Studio Installer out of existence from my laptop, I'd be forever grateful. Failing that, help to solve the mentioned error would also be very much appreciated. MTIA! 😄

P.S: **Is there somewhere besides mpc-hc -> Project Properties -> Linker -> Input that I should remove lib(royal pain in the)ass from?**

**Comment by clsid2** [comment]
Make sure that you have latest source code. There were some changes a few days ago that might have fixed this. I don't have VS2017, so I can't test.

The libass stuff is not yet actively used by MPC-HC, so for now you could also ignore this error.

**Comment by clsid2** [comment]
I have made another change.

**Comment by kenny1983** [comment]
I read the whole linked issue, so yes I'm aware of everything you just said. Thanks anyway for replying 😄 I've had to move on to other things for today but when I get the chance, I'm going to attempt to add debugging symbols and other necessary stuff to the Release Lite configuration. Then I should *hopefully* be able to step through code.

That's the only thing I'm really concerned about, since the project is so huge. Being able to step through code will allow me to learn more about how the project actually works, then *hopefully* I'll be able to contribute in a meaningful way by the end of next week.

**Comment by kenny1983** [comment]
> I have made another change.

Cool, I'll pull when I get a chance and hopefully that will help 😄. I initally forked the project well after your 28 Dec changes, but yeah...fingers crossed that today's change is the final one needed!

**Comment by clsid2** [comment]
I have fixed the problems with VS2019 16.8.x

One of the main causes was the use of `/std:c++latest` which I have now replaced with `/std:c++17`

**Comment by adipose** [comment]
https://github.com/clsid2/mpc-hc/pull/834

Interesting, maybe duplicated work.

**Comment by kenny1983** [comment]
> I have fixed the problems with VS2019 16.8.x
> 
> One of the main causes was the use of `/std:c++latest` which I have now replaced with `/std:c++17`

Awesome! I'll check it out now and LYK if I still have issues.
