### ISSUE TITLE
internal subtitle renderer problems

### ISSUE THREAD

**Issue by realfinder** [clsid2/mpc-hc#974]
hi
1. seems it break how vsfilter should work when no YCbCr Matrix in the .ass file
using [ctest.zip](https://github.com/clsid2/mpc-hc/files/6097489/ctest.zip)
it will be
![image](https://user-images.githubusercontent.com/2512153/110246963-ddde4080-7f7a-11eb-9a56-71490063614e.png)
it should be
![image](https://user-images.githubusercontent.com/2512153/110247014-0a925800-7f7b-11eb-968d-13bf85e54714.png)

2. it seems it has same problem as the one here https://github.com/pinterf/xy-VSFilter/issues/16

**Comment by clsid2** [comment]
You should just fix your .ass by specifying the matrix.

Changing the behavior of the subtitle renderer will likely cause other files to break.

**Comment by realfinder** [comment]
no, even mpv show it as https://user-images.githubusercontent.com/2512153/110247014-0a925800-7f7b-11eb-968d-13bf85e54714.png

same for using external vsfilter

> 
> 
> 
>     [Script Info]
>     YCbCr Matrix: TV.601
>     YCbCr Matrix: TV.709
>     YCbCr Matrix: PC.601
>     YCbCr Matrix: PC.709
>     YCbCr Matrix: None
>     'YCbCr Matrix' as well as override settings in the GUI, only have an effect on YCbCr subtitle output. The video is always untouched.
> 
>     TV.601 = Output BT.601 with 16-235 YCbCr level range
>     TV.709 = Output BT.709 with 16-235 YCbCr level range
>     PC.601 = Output BT.601 with 0-255 YCbCr level range
>     PC.709 = Output BT.709 with 0-255 YCbCr level range
>     None = Output BT.601 or BT.709 with 16-235 YCbCr level range based on video resolution
> 
>     If 'YCbCr Matrix' is missing from a script, xy-VSFilter will use TV.601 for legacy script compatibility. It is highly recommended to leave the GUI settings at their defaults of Auto | Auto for 'YCbCr level range' | 'YCbCr matrix'. The Auto settings obey the 'YCbCr Matrix' tag (if present), else fallback to TV.601 as decribed above.

**Comment by clsid2** [comment]
Fixed

**Comment by realfinder** [comment]
> Fixed

Hi again!
seems this problem is back since https://github.com/clsid2/mpc-hc/releases/tag/1.9.24 (1.9.23 was work fine)

maybe because of "Properly handle NONE as value for YCbCr Matrix subtitle header"?

but "None" =/= "'YCbCr Matrix' is missing from a script" (different cases)

"None" is work ok since 1.9.24 (it was not ok in 1.9.23 or older)

in MPV both "'YCbCr Matrix' is missing from a script" and "None" cases work fine

**Comment by clsid2** [comment]
NONE means: colors are RGB and do no color mangling.

**Comment by realfinder** [comment]
> NONE means: colors are RGB and do no color mangling.

sure, but my problem is not with the "NONE" but with the .ass script that has no "YCbCr Matrix" at all

**Comment by clsid2** [comment]
No matrix renders as 601.

Disable libass option. I am not interested in implementing color mangling functionality for libass.

Use MPC Video Renderer.
Don't use madvr, as that completely fucks up the colors.

**Comment by realfinder** [comment]
> Disable libass option.

its disabled by default in my system

> Use MPC Video Renderer.

thanks! that seems fix it (it was setted to Enhanced Video Renderer, by default?)

> I am not interested in implementing color mangling functionality for libass.

> Don't use madvr, as that completely fucks up the colors.

I didnt see madvr in my system! is it renamed as "Enhanced Video Renderer"? anyway if you dont want to fix them maybe make MPC Video Renderer as default?
